name: sql_engine
description: A thin yet powerful SQLite layer for Dart & Flutter.
version: 2.0.3
homepage: https://github.com/snbrb/sql_engine
repository: https://github.com/snbrb/sql_engine
issue_tracker: https://github.com/snbrb/sql_engine/issues

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  analyzer: ^7.4.4
  build: ^2.4.0
  flutter:
    sdk: flutter
  meta: ^1.16.0
  path: ^1.9.1
  source_gen: ^2.0.0
  sqlite3: ^2.7.6
  sqlite3_flutter_libs: ^0.5.33
  sqlite3_web: ^0.3.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

topics:
  - sqlite
  - sqlite-flutter
  - sqlite3
  - sql
  - database
