name: sql_engine
description: A thin yet powerful, zero-reflection SQLite layer for Dart & Flutter.
version: 1.0.0
homepage: https://github.com/snbrb/sql_engine
repository: https://github.com/snbrb/sql_engine
issue_tracker: https://github.com/snbrb/sql_engine/issues

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqlite3: ^2.7.5
  meta: ^1.16.0
  build: ^2.4.0
  source_gen: ^2.0.0
  analyzer: ^6.7.0
  path: ^1.9.1
  sqlite3_flutter_libs: ^0.5.32
  sqlite3_web: ^0.3.1

dev_dependencies:
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

topics:
  - sql
  - sqlite
  - database
  - flutter
  - orm